### ISSUE TITLE
Higher level serialization support

### ISSUE THREAD

**Issue by robertbastian** [BurntSushi/regex-automata#20]
Serializing is only possible to `[u8]` right now, which means for any larger state sizes I have to deal with endianness and unsafe code.

Ideally (for us), `DenseDFA` would implement `serde::{Deserialize, Serialize}`. I can understand however if you don't want to support a specific serialization framework. In that case, could we add a higher-level serialize-to-`[S]` function (which I can then pass to Serde)?

**Comment by BurntSushi** [comment]
@sffc With regard to the safety issue, that will be resolved in `regex-automata 0.2`. See the doc link above for the in-progress API. There is a safe `from_bytes` and an unsafe `from_bytes_unchecked`.

I've given this issue more thought and here's the fundamental problem as I see it: the (de)serialization APIs in this crate were designed with zero-copy in mind. That means you can build a DFA from a `&[u8]` and the DFA will be tied to the lifetime of `&[u8]`. In other words, DFA deserialization is done from a `&[u8]` without any sort of modification of the `&[u8]` itself at all. More to the point, it's done without any allocs whatsoever, so as to work in a `no_std`/`no_alloc` environment.

Basically, what this means is that those `from_bytes` APIs really can't do any byte swapping. At minimum, some new API that accepts a `&mut [u8]` would have to be introduced. The byte swapping cannot be done by callers, since the logical representation is really just a sequence of bytes with _parts_ of it being sequences of, say, `u32`.

>  Ideally we can always store the bytes as LE and swap them to BE if needed at runtime.

If there was an API that took a `&mut [u8]`, detected its endianness and the current host endianness and did byte-swapping if necessary, would that work for y'all?

> Also, Serde itself doesn't make any guarantees about the alignment of the byte buffer.

This is definitely a problem. We can't do zero-copy deserialization without alignment guarantees. I don't see a way to relax that constraint without introducing a copy. This perhaps feels like the highest priority issue since it seems the most difficult to work around without introducing a copy of the DFA in memory.

**Comment by sffc** [comment]
[ZeroVec](https://docs.rs/zerovec/0.4.1/zerovec/) solves the alignment and endianness problems by aligning and swapping in the `.get()` function, returning things by value instead of by reference.  Benchmarks can be found on the docs.rs page (it's very slightly slower than a "normal" slice).

**Comment by sffc** [comment]
> I've given this issue more thought and here's the fundamental problem as I see it: the (de)serialization APIs in this crate were designed with zero-copy in mind. That means you can build a DFA from a `&[u8]` and the DFA will be tied to the lifetime of `&[u8]`. In other words, DFA deserialization is done from a `&[u8]` without any sort of modification of the `&[u8]` itself at all. More to the point, it's done without any allocs whatsoever, so as to work in a `no_std`/`no_alloc` environment.

To be clear! I'm absolutely in favor of zero-copy, no-alloc deserialization, and it is one of the main things that attracts me to this crate!  Thank you for putting value on that.

This is a value that is shared by the ICU4X project @Manishearth and I are working on.  Since we wanted to use Serde in order to make serialization more scalable and flexible, we had to solve many of these same issues, and ZeroVec (as mentioned above) was our solution to that.

**Comment by BurntSushi** [comment]
OK, I see where you're going now. In essence, change the representation to one that is endian independent and implement byte-swapping on access and use unaligned loads. Unfortunately, this suggestion is quite invasive, and because it impacts perf critical code, it also requires re-doing perf analysis. And this is all in an area of the code that was _just_ rewritten. The timing here is really just quite unfortunate. I might have been able to entertain experimenting with this about a year ago, but there's no way I have the stomach to revisit this any time soon. This would _certainly_ have an impact (likely non-trivial) on big-endian systems at the very least, and being forced into unaligned loads everywhere seems likely to have an impact on all systems. The codegen for the DFA inner loop is rather sensitive and critical. Eliding bounds checks, for example, results in a measurable improvement.

I grant your approach is feasible, but as a practical matter, there's no way I'm even going to attempt it for some time. I would ask that you look toward answers that require less effort. Unfortunately, I can't think of any. It seems like you need to sacrifice memory at deserialization time with a copy to deal with alignment, along with either a new API in `regex-automata` that does byte swapping, or storage of both the LE and BE representations with a dispatch depending on the target system at deserialization time. You could elide the copy if you stored both the LE and BE representations if you used a sparse DFA, since a sparse DFA has no alignment requirements. That's something. It also uses potentially substantially less space and is still quite fast.

This is all quite unfortunate. I wish I had the Serde use case in mine back in the design stages.

**Comment by sffc** [comment]
> You could elide the copy if you stored both the LE and BE representations if you used a sparse DFA, since a sparse DFA has no alignment requirements. That's something. It also uses potentially substantially less space and is still quite fast.

We're definitely optimizing for data size, so likely to use the Sparse DFA anyway. So this solves the alignment requirement.  In many ways, that's the harder of the two problems.

For endianness, I think either of the following solutions are totally doable in the medium term:

1. Store both the LE and the BE versions of the Sparse DFA and choose the appropriate one at runtime
2. Store only the LE version, and on BE systems, copy it onto the heap via a new byte swapping API

The downside of (1) of course is that we double data storage requirements for what is mostly an edge case these days (big-endian systems).  So I think (2) is the best solution.  And there is of course always the possibility to optimize this in the future now that we've raised Serde as a use case.

**Comment by BurntSushi** [comment]
> Store only the LE version, and on BE systems, copy it onto the heap via a new byte swapping API

Aye, okay. I _think_ this can be done relatively easily in the short term. I'd do my best to review a merge a PR that did this for `0.1`, and then I could own porting it to `0.2` if y'all need this sooner rather than later.

**Comment by sffc** [comment]
@BurntSushi In ICU4X we're using regex-automata 0.2 via a git commit hash (with LE-only support for the time being).  We're hoping to push an interim release of ICU4X to crates.io soon.  For planning purposes, could you share an idea of when we'd be able to use regex-automata 0.2 via crates.io?  Thank you again!

**Comment by BurntSushi** [comment]
I don't know. I work on this in my free time. I had hoped to have it done by now, but having a 15 month old at home has slowed me way down. :-)

I have made a lot of progress, but my originally planned scope is quite large and there's still a lot left to do.

One possibility is that I publish what I have as `0.2`, and target `0.3` for my originally planned scope. With `0.2` including the re-designed API for DFAs, in addition to the hybrid NFA/DFA API. It's a bit more overhead for me to do that, but you might otherwise be waiting a very long time if I don't. How much would that help y'all?

**Comment by sffc** [comment]
Yes, it would be useful to us if you could release what you currently have!  The big things in 0.2 for us were the new APIs for (sparse) DFAs, including the new fallible `DFA::from_bytes` function.  This would unblock the ICU4X release cycle, and we can upgrade to 0.3 once it is ready.

**Comment by robertbastian** [comment]
Friendly ping

**Comment by Manishearth** [comment]
Thank you so much! :smile:
