### ISSUE TITLE
NonStreaming find over multiple slices

### ISSUE THREAD

**Issue by ratmice** [BurntSushi/regex-automata#23]
There are a lot of issues in the regex crate, most prominently https://github.com/rust-lang/regex/issues/425 which discuss streaming regex, but within it there is discussion of https://github.com/rust-lang/regex/issues/425#issuecomment-860040036 Cursor API,
I have been thinking a bit through the case where we have a `Rope`, and have something with an equivalence to `String`.  But don't have a single slice to give `find_*`.

In the specific `Cursor` comment, I was thinking about a rather different API than the iteration/cursor based one,
where regex just deals with absolute coordinates treating it as one logically contiguous space, where it retrieves 
which has an API such as:

```
trait DeltaSlices {
    // Returns a (slice, delta)
    // Returns a single unique slice whose range overlaps bounds
    // where slice[bounds.start - delta..slice.len()] is a valid range over the returned slice.

    fn first_slice(&self, bounds: std::ops::Range<usize>) -> Option<(&[u8], usize)>;
    // The cumulative sum of slice lengths accessible from this.
    fn total_len(&self) -> usize;
}

impl DeltaSlices for &[u8] {
    fn first_slice(&self, _: std::ops::Range<usize>) -> Option<(&[u8], usize)> {
        Some((self, 0))
    }
    fn total_len(&self) -> usize {
        self.len()
    }
}
```
Edit: FWIW I haven't really thought through lifetimes at all on this,
or what with the stablization of GATs a lending style iterator API could provide instead

I'm curious what your thoughts are on this, or making the API more flexible for things such as ropes, but are perhaps more tractable than a fully general streaming API.  Given the API being somewhat in transition at this point in time with being after 0.2 but before 0.3 release, If you have any thoughts on both when good timing, and upon which branch would be a good place to start tinkering with such an API, i would be curious to do so.

It may not be a good idea, but it seemed perhaps less branchy than the `Cursor` api which was discussed, and also keeps things like 'Chunk indexes' from infecting public API, since conversion between absolute and slice relative coordinates is entirely local to the trait.

I guess my biggest gripe with the API is that it isn't `Iterator`-like enough in the sense that it looks essentially random access.
And presents little opportunity for cursor advancement (I find this a funny gripe, because perhaps one gripe with the cursor was that it was too iterator like and not random-access enough, see below quote).  

>So overall, this API for describing streams seems insufficient. At every turn we make, the search implementations seem to be begging for random access.

Anyhow.

**Comment by BurntSushi** [comment]
Speaking to logistics first: my main priority right now is getting `regex-automata` into a place where `regex` can replace most of its internals with uses of `regex-automata`. That doesn't include streaming. I just don't have the bandwidth for it right now. With that said, one of the goals of `regex-automata` is that you _don't have to use the higher level search routines_. All of the regex engines (including the NFA engines, which are WIP) expose enough of their internals to write your own search routines. For folks needing the streaming use case, I would really love it if they wrote their own search routines first. Then we can have a "meeting of the minds" to see how we might unify them, if at all. Writing search routines for the DFA based regex engines is not trivial in an absolute sense, but it is trivial when compared to everything that goes into turning a regex pattern string into a finite state machine. The NFA search routines will be a bit more involved to write outside of the crate, but it is nevertheless an intended option that this crate will provide.

It's also worth saying that since I see `regex-automata` as an "expert level" crate, I don't see many people using it (at least, not near as much as `regex` itself). For that reason, I don't prioritize the minimization of churn nearly as much, so long as there are no breaking changes in `regex` proper. I treat `regex-syntax` similarly. I have no problems releasing breaking changes to `regex-syntax` _at the API level_ at whatever cadence is convenient. That's why `regex-syntax` is specifically not a public dependency of `regex` (nor will `regex-automata` be). So don't worry too much about stuff not being in `regex-automata 0.3`. I won't be nearly as resistant to evolving its APIs as I am with `regex`.

Also, I kinda think it would be better to keep this discussion in https://github.com/rust-lang/regex/issues/425, since it's all pretty inter-connected. Spreading it over two issues makes it kind of annoying to follow the discussion. Also, more people are likely watching that regex issue, which gives more eyes on things.

As for your specific API proposal... I'm not quite sure that I grok it to be honest. It's not clear to me how it would be used by the regex engines. Also, your doc comments appear to be out of sync with the type signatures, which makes things a bit more confusing.

**Comment by ratmice** [comment]
I updated the doc comment, but since you think it's better to keep it to #425 i'll just close this.

My thinking was the case I'm working with *isn't* really streaming, it is just dealing with multiple slices.
As such I was thinking it would be good to have a place to discuss expanding on the current e.g. [find_leftmost](https://docs.rs/regex-automata/latest/regex_automata/dfa/regex/struct.Regex.html#method.find_leftmost) which would allow it to work over multiple slices without actually having to/or trying to solve the fully general streaming case over infinite or incomplete strings.

Anyhow, closing this as-per your wishes

**Comment by BurntSushi** [comment]
Yeah, feel free to re-post this into that issue and I can re-post my response.

And yes, I think it is valuable to talk about discontiguous strings as a use case that is distinct from the fully general streaming case. It would be nice to unify them, but it's very plausible that the former case can be dealt with more simply. (I think I talk about this a bit in the regex issue.)

**Comment by BurntSushi** [comment]
Also, note this comment https://github.com/rust-lang/regex/issues/425#issuecomment-860277747 where I call out that `Cursor` doesn't solve the fully general stream problem. Rather, in theory, it could be implemented via discontiguous strings or with, e.g., a `std::fs::File`. But _not_ a arbitrary `std::io::Read`.
