### ISSUE TITLE
Leftmost Longest search

### ISSUE THREAD

**Issue by RustyYato** [BurntSushi/regex-automata#31]
I was reading through this crate to see if I could create an alternative to [logos](https://crates.io/crates/logos), when I stumbled across this note about leftmost-longest search. Which was discouraging. (Since lexers would want leftmost-longest semantics).
https://github.com/BurntSushi/regex-automata/blob/c61a6d0f19b013dc832755375709023dfb9d5a8f/src/util/matchtypes.rs#L21-L35

However, when I tried out some specific combinations with the dense DFA,

```rs
regex_automata::dfa::dense::Config::new()
    .anchored(true)
    .minimize(true)
    .match_kind(regex_automata::MatchKind::All)
```

and running the dfa with `find_leftmost_fwd`, I seem to be getting leftmost longest semantics.

specifically I tried out this snippet

```rs
fn main() {
    let dfa = DfaBuilder::new()
        .configure(
            regex_automata::dfa::dense::Config::new()
                .anchored(true)
                .minimize(true)
                .match_kind(regex_automata::MatchKind::All),
        )
        .build_many(&[
            // for my use-case I want multiple patterns, but this example only uses 1
            r"\w|\w\w",
        ])
        .unwrap();

    let input = "hello#!!!!,,!!,,asdf!fdsd";
    let output = dfa.find_leftmost_fwd(input.as_bytes()).unwrap();
    dbg!(output);
}
```

and I get the following output 

```rs
output = Some(
    HalfMatch {
        pattern: PatternID(
            0,
        ),
        offset: 2,
    },
)
```

But if we are using the leftmost longest semantics, since the `\w` pattern is the leftmost pattern, it should take precedence right? 
Now, this is great for me, but I want to understand if this is expected behavior: using `match_kind::All` + `anchored` with `find_leftmost_fwd` is expected to give leftmost-longest semantics?

**Comment by BurntSushi** [comment]
Yes, the behavior you're seeing is correct. The difference between `MatchKind::All` and a hypothetical `MatchKind::LeftmostLongest` is that the latter would support non-greedy matching. That in turn is required to make unanchored searches work (given this crate's architecture), since unanchored searches work as if the pattern begins with a `(?s-u:.*?)`.`

Also, if you can, I would suggest waiting to use this crate until `0.3` is released. That will happen roughly when this PR gets merged: https://github.com/rust-lang/regex/pull/978

I have a naive belief that it will happen this month, but we'll see.

**Comment by RustyYato** [comment]
Ah, that does make sense, I hadn't considered non-greedy matches. Thanks!
